### PR TITLE
Update Gym options

### PR DESCRIPTION
**Pull request by briancain**

### CODE REVIEW

**Comment by briancain** [comment]
I can't in good faith recommend Loprinzis anymore as a place that people should patronize. I've replaced it with a couple more suggestions that are much better.

**Comment by mckern** [comment]
giphy 1

I will take your recommendations under _advisement_

**Comment by mckern** [comment]
Do you know if both of those gyms have day passes available for our out-of-town friends?

**Comment by briancain** [comment]
@mckern - yep! Both offer punch cards and or drop in prices

**Comment by ajwood-acquia** [comment]
@briancain what's wrong with loprinzi's?

I promise I'm not fishing for an argument. I'm a loprinzi's member but I'm pretty new to the gym thing in general, I don't have any strong opinions about good and bad. Just wondering what changed your feelings about it?

**Pull request merged**
